import './accountCommands/gui_commands.js'
import './loginCommands/gui_commands.js'
import './movementCommands/gui_commands.js'
import './summaryCommands/gui_commands.js'
import './utils/commands.js'